source 'https://rubygems.org'
source 'https://rails-assets.org'

gem 'rails', '~> 4.0'
gem 'sqlite3'
gem 'uglifier'
gem 'inherited_resources'
gem 'active_model_serializers'
gem 'kaminari'

gem 'feedbag'
gem 'feed-normalizer'
gem 'readability_parser'
gem 'nokogiri'
gem 'nestful'
gem 'sucker_punch'

gem 'jade'
gem 'slim-rails'

gem 'sass-rails', '~> 4.0.2'
gem 'breakpoint'
gem 'compass-rails'
gem 'font-awesome-rails'

gem 'coffee-rails'

gem 'rails-assets-jquery'
gem 'rails-assets-fastclick'
gem 'rails-assets-moment'
gem 'rails-assets-hammerjs'
gem 'rails-assets-mousetrap'
gem 'rails-assets-highlightjs'
gem 'rails-assets-normalize-css'
gem 'rails-assets-angular'
gem 'rails-assets-angular-moment'
gem 'rails-assets-angular-hammer'

gem 'puma'
gem 'foreman'
